### ISSUE TITLE
Gift Aid Info not displaying on Front End

### ISSUE THREAD

**Issue by stuartleech** [fm-ticketing/dawn-shopify-theme#74]
<img width="739" alt="Screenshot 2024-01-18 at 17 40 33" src="https://github.com/fm-ticketing/dawn-shopify-theme/assets/15141003/77e4d49e-dc74-41c9-9763-3dc486f71a26">

Info text in box but on the front end not displayed:

<img width="822" alt="Screenshot 2024-01-18 at 17 41 12" src="https://github.com/fm-ticketing/dawn-shopify-theme/assets/15141003/7cd34ade-7a6a-496e-91e9-07b706c0c8c7">

**Comment by katjam** [comment]
I'll take a look at this today.

**Comment by katjam** [comment]
![image](https://github.com/fm-ticketing/dawn-shopify-theme/assets/861172/554b1b96-28aa-4c70-83f2-bf245898325c)

**Comment by katjam** [comment]
Checking variable names against:
![image](https://github.com/fm-ticketing/dawn-shopify-theme/assets/861172/31d47b7a-d77a-40a4-b8d8-3e2efbc1db15)

**Comment by katjam** [comment]
Fixed in the content - there is some argument that the code should use _info rather than _text because of the field title but this was the simplest fix and now matches data on staging.
****
![image](https://github.com/fm-ticketing/dawn-shopify-theme/assets/861172/e859775d-0200-4499-8578-90a5b33035c2)

**Comment by katjam** [comment]
Verified:
![image](https://github.com/fm-ticketing/dawn-shopify-theme/assets/861172/6ba46cca-00c7-47b7-af89-e893a2ebc3e1)
